server:
  servlet:
    context-path: /api/v1
    application-display-name: ${APPLICATION_NAME}
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      resolve-lazily: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
